# Systemd environment file for the otelcol-contrib service

# Command-line options for the otelcol-contrib service.
# Run `/usr/bin/otelcol-contrib --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otelcol-contrib/config.yaml"
GRAFANA_CLOUD_OTLP_ENDPOINT="https://otlp-gateway-prod-ap-south-1.grafana.net/otlp"
GRAFANA_CLOUD_INSTANCE_ID="876457"
GRAFANA_CLOUD_API_KEY= <YOUR_KEY>
GRAFANA_CLOUD_BASIC_AUTH_HEADER="Basic ODc2NDU3OmdsY19leUp2SWpvaU1UQTNNakl3TUNJc0ltNGlPaUp2ZEd4d0xXZHlZV1poYm1FaUxDSnJJam9pTnpjNVQyNVdOVk53ZGtVeVV6STRUREJzTW10c01YZGpJaXdpYlNJNmV5SnlJam9pY0hKdlpDMWhjQzF6YjNWMGFDMHhJbjE5"
HOSTNAME="f6b980b1721c.mylabserver.com"
