name: Cinc - datadog_custom Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "automation/cinc/datadog_custom/**"
      - ".github/workflows/cinc-datadog_custom-validation.yml"

  pull_request:
    branches:
      - main
      - develop
    paths:
      - "automation/cinc/datadog_custom/**"
      - ".github/workflows/cinc-datadog_custom-validation.yml"

jobs:
  validate:
    name: Validate datadog_custom
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: automation/cinc/datadog_custom

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
